{% set name = "mesher" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mesher-{{ version }}.tar.gz
  sha256: 8c6635cdcd3426fa1583a2b59d4546e209a324754f32c487da301c03b6170726

build:
  entry_points:
    - mesher = mesher:main
    - mesh2shp = mesher.tools.mesh2shp:main
    - mesh2vtu = mesher.tools.mesh2vtu:main
    - mesh2merge = mesher.tools.meshmerge:main
    - meshpermutation = mesher.tools.meshpermutation:main
    - meshstats = mesher.tools.meshstats:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - scikit-build-core
    - pip
    - cgal-cpp
    - libboost-devel
    # pin due to current incompatibility with vtk&proj 9.4.0 
    # conda-forge/gdal-feedstock/issues/911
    - libgdal <3.8.5 # 
    - metis
  run:
    - python
    - vtk
    - numpy
    - scipy
    - matplotlib-base
    - cloudpickle
    - gdal
    - metis
    - metis-python
    - mpi4py
    - natsort
    - gmp

test:
  imports:
    - mesher
  commands:
    - pip check
    - mesher
  requires:
    - pip

about:
  home: https://github.com/Chrismarsh/mesher
  summary: Mesher is a novel multi-objective unstructured mesh generation software that allows mesh generation to be generated from an arbitrary number of hydrologically important features while maintaining a variable spatial resolution. Triangle quality is guaranteed as well as a smooth graduation from small to large triangles.
    Including these additional features resulted in a better representation of spatial heterogeneity versus classic topography-only mesh generation.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Chrismarsh
